using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GlobalAzure2021
{
    public class Model
    {
        public List<Movie> Movies { get; set; }
        public Model()
        {
            Movies = new List<Movie> {
                new Movie { MovieId = 1, Name = "Buscando a Nemo (2003)", Type = "genero 9" },
new Movie { MovieId = 2, Name = "Ciudad de Dios (2002)", Type = "genero 6" },
new Movie { MovieId = 3, Name = "Hable con ella (2002)", Type = "genero 1" },
new Movie { MovieId = 4, Name = "El Señor de los Anilllos (2001 – 2003)", Type = "genero 4" },
new Movie { MovieId = 5, Name = "Kandahar (2001)", Type = "genero 4" },
new Movie { MovieId = 6, Name = "La mirada de Ulises (1995)", Type = "genero 1" },
new Movie { MovieId = 7, Name = "Chunking Express (1994)", Type = "genero 8" },
new Movie { MovieId = 8, Name = "Drunken Master II (1994)", Type = "genero 7" },
new Movie { MovieId = 9, Name = "Pulp Fiction (1994)", Type = "genero 2" },
new Movie { MovieId = 10, Name = "Adiós a mi concubina (1993)", Type = "genero 10" },
new Movie { MovieId = 11, Name = "La lista de Schindler (1993)", Type = "genero 4" },
new Movie { MovieId = 12, Name = "Leolo (1992)", Type = "genero 2" },
new Movie { MovieId = 13, Name = "Sin Perdón (1992)", Type = "genero 2" },
new Movie { MovieId = 14, Name = "Uno de los nuestros (1990)", Type = "genero 10" },
new Movie { MovieId = 15, Name = "Muerte entre las flores (1990)", Type = "genero 5" },
new Movie { MovieId = 16, Name = "El decálogo (1989)", Type = "genero 8" },
new Movie { MovieId = 17, Name = "Nakayan (1987)", Type = "genero 10" },
new Movie { MovieId = 18, Name = "El cielo sobre Berlín (1987)", Type = "genero 6" },
new Movie { MovieId = 19, Name = "La mosca (1986)", Type = "genero 6" },
new Movie { MovieId = 20, Name = "El detective cantante (1986)", Type = "genero 1" },
new Movie { MovieId = 21, Name = "1985 – 1966", Type = "genero 10" },
new Movie { MovieId = 22, Name = "Brazil (1985)", Type = "genero 8" },
new Movie { MovieId = 23, Name = "La Rosa púrpura del Cairo (1985)", Type = "genero 8" },
new Movie { MovieId = 24, Name = "Blade Runner (1992)", Type = "genero 10" },
new Movie { MovieId = 25, Name = "E.T. El extraterrestre (1982)", Type = "genero 10" },
new Movie { MovieId = 26, Name = "Berlin Alexanderplatz (1980)", Type = "genero 3" },
new Movie { MovieId = 27, Name = "Mi tío de América (1980)", Type = "genero 10" },
new Movie { MovieId = 28, Name = "Toro salvaje (1980)", Type = "genero 8" },
new Movie { MovieId = 29, Name = "La Guerra de las Galaxias (1977)", Type = "genero 10" },
new Movie { MovieId = 30, Name = "Taxi Driver (1976)", Type = "genero 8" },
new Movie { MovieId = 31, Name = "Barry Lyndon (1975)", Type = "genero 4" },
new Movie { MovieId = 32, Name = "Chinatown (1974)", Type = "genero 5" },
new Movie { MovieId = 33, Name = "La noche americana (1973)", Type = "genero 3" },
new Movie { MovieId = 34, Name = "El Padrino (Parte I y II) (1972, 1974)", Type = "genero 6" },
new Movie { MovieId = 35, Name = "Aguirre, la cólera de Dios (1972)", Type = "genero 7" },
new Movie { MovieId = 36, Name = "El discreto encanto de la burguesía (1972)", Type = "genero 2" },
new Movie { MovieId = 37, Name = "A touch of Zen (1971)", Type = "genero 8" },
new Movie { MovieId = 38, Name = "Érase una vez en América (1968)", Type = "genero 4" },
new Movie { MovieId = 39, Name = "Bonnie and Clide (1967)", Type = "genero 6" },
new Movie { MovieId = 40, Name = "Mouchette (1967)", Type = "genero 1" },
new Movie { MovieId = 41, Name = "Trenes rigurosamente vigilados (1966)", Type = "genero 3" },
new Movie { MovieId = 42, Name = "1966 – 1954", Type = "genero 5" },
new Movie { MovieId = 43, Name = "El bueno, el feo y el malo (1966)", Type = "genero 9" },
new Movie { MovieId = 44, Name = "Persona (1966)", Type = "genero 6" },
new Movie { MovieId = 45, Name = "Bande à part (1964)", Type = "genero 7" },
new Movie { MovieId = 46, Name = "Teléfono rojo, volamos hacia Moscú (1964)", Type = "genero 7" },
new Movie { MovieId = 47, Name = "Qué noche la de aquel día (A hard day’s night) (1964)", Type = "genero 6" },
new Movie { MovieId = 48, Name = "Charada (1963)", Type = "genero 10" },
new Movie { MovieId = 49, Name = "8 y ½ (1963)", Type = "genero 9" },
new Movie { MovieId = 50, Name = "Lawrence de Arabia (1962)", Type = "genero 9" },
new Movie { MovieId = 51, Name = "El mensajero del miedo (1962)", Type = "genero 2" },
new Movie { MovieId = 52, Name = "Yoyimbo (1961)", Type = "genero 2" },
new Movie { MovieId = 53, Name = "Psicosis (1960)", Type = "genero 3" },
new Movie { MovieId = 54, Name = "Los cuatrocientos golpes (1959)", Type = "genero 4" },
new Movie { MovieId = 55, Name = "Con faldas y a lo loco (1959)", Type = "genero 6" },
new Movie { MovieId = 56, Name = "Pyassa (1957)", Type = "genero 3" },
new Movie { MovieId = 57, Name = "Chantaje en Broadway (1957)", Type = "genero 5" },
new Movie { MovieId = 58, Name = "La invasión de los ladrones de cuerpos (1956)", Type = "genero 3" },
new Movie { MovieId = 59, Name = "Centauros del desierto (1956)", Type = "genero 10" },
new Movie { MovieId = 60, Name = "La trilogía de Apu (1955, 1956, 1959)", Type = "genero 4" },
new Movie { MovieId = 61, Name = "Sonrisas de una noche de verano (1955)", Type = "genero 1" },
new Movie { MovieId = 62, Name = "La ley del silencio (1954)", Type = "genero 5" },
new Movie { MovieId = 63, Name = "1953 – 1940", Type = "genero 2" },
new Movie { MovieId = 64, Name = "Cuentos de Tokio (1953)", Type = "genero 2" },
new Movie { MovieId = 65, Name = "Historias de la luna pálida de agosto (1953)", Type = "genero 8" },
new Movie { MovieId = 66, Name = "Vivir (1952)", Type = "genero 4" },
new Movie { MovieId = 67, Name = "Cantando bajo la lluvia (1952)", Type = "genero 1" },
new Movie { MovieId = 68, Name = "Umberto D (1952)", Type = "genero 7" },
new Movie { MovieId = 69, Name = "Un tranvía llamado deseo (1951)", Type = "genero 3" },
new Movie { MovieId = 70, Name = "En un lugar solitario (1950)", Type = "genero 6" },
new Movie { MovieId = 71, Name = "Ocho sentencias de muerte (1949)", Type = "genero 10" },
new Movie { MovieId = 72, Name = "Al rojo vivo (1949)", Type = "genero 7" },
new Movie { MovieId = 73, Name = "Retorno al pasado (1949)", Type = "genero 2" },
new Movie { MovieId = 74, Name = "Qué bello es vivir (1946)", Type = "genero 7" },
new Movie { MovieId = 75, Name = "Encadenados (1946)", Type = "genero 8" },
new Movie { MovieId = 76, Name = "Les enfants du paradise (1945)", Type = "genero 4" },
new Movie { MovieId = 77, Name = "Detour (1945)", Type = "genero 9" },
new Movie { MovieId = 78, Name = "Perdición (1944)", Type = "genero 7" },
new Movie { MovieId = 79, Name = "Cita en San Luis (1944)", Type = "genero 4" },
new Movie { MovieId = 80, Name = "Casablanca (1942)", Type = "genero 3" },
new Movie { MovieId = 81, Name = "Ciudadano Kane (1941)", Type = "genero 6" },
new Movie { MovieId = 82, Name = "Las tres noches de Eva (1941)", Type = "genero 4" },
new Movie { MovieId = 83, Name = "Luna nueva (1940)", Type = "genero 5" },
new Movie { MovieId = 84, Name = "1940 – 1924", Type = "genero 2" },
new Movie { MovieId = 85, Name = "Pinocho (1940)", Type = "genero 5" },
new Movie { MovieId = 86, Name = "El bazar de las sorpresas (1940)", Type = "genero 1" },
new Movie { MovieId = 87, Name = "Ninotchka (1939)", Type = "genero 10" },
new Movie { MovieId = 88, Name = "Olimpia I y II (1938)", Type = "genero 3" },
new Movie { MovieId = 89, Name = "La pícara puritana (1937)", Type = "genero 10" },
new Movie { MovieId = 90, Name = "Margarita Gautier (1936)", Type = "genero 9" },
new Movie { MovieId = 91, Name = "Le Crime de Monsieur Lange (1936)", Type = "genero 8" },
new Movie { MovieId = 92, Name = "Desengaño (1936)", Type = "genero 8" },
new Movie { MovieId = 93, Name = "En alas de la danza (1936)", Type = "genero 5" },
new Movie { MovieId = 94, Name = "La novia de Frankenstein (1935)", Type = "genero 2" },
new Movie { MovieId = 95, Name = "It's A Gift (1934)", Type = "genero 7" },
new Movie { MovieId = 96, Name = "Baby Face (1933)", Type = "genero 5" },
new Movie { MovieId = 97, Name = "King Kong (1933)", Type = "genero 3" },
new Movie { MovieId = 98, Name = "Luces de la ciudad (1931)", Type = "genero 7" },
new Movie { MovieId = 99, Name = "El Cameraman (1929)", Type = "genero 6" },
new Movie { MovieId = 100, Name = "Y el mundo marcha… (1928)", Type = "genero 8" },
new Movie { MovieId = 101, Name = "La última orden (1928)", Type = "genero 4" },
new Movie { MovieId = 102, Name = "Metrópolis (1927)", Type = "genero 10" },
new Movie { MovieId = 103, Name = "El joven Sherlock Holmes (1924)", Type = "genero 9" }
            };
        }

    }
       
}
